Функция test_4 с аргументами () и {} была вызвана 2024-07-02 20:22:26 и вернула 'Тест пройден успешно'
